### ISSUE TITLE
Add -novid to skip intro banners

### ISSUE THREAD

**Issue by tmp64** [thelivingdiamond/Chairloader#95]
Add `-novid` command line argument that automatically skips into banners without removing any files.

**Comment by colby-boucher** [comment]
This probably has nothing to do with Chairloader itself, but this would be particularly nice for us Linux weirdos because for whatever reason, running the game through Proton, the game simply "waits" for the intro videos to play and never moves on to the menu if they're gone. ...Unless you force the game closed, in which case the menu music starts, the screen remains black, and any evidence of the game running seems invisible to Linux itself. It's pretty odd.
